- id: primary-murano-node
  type: group
  role: [primary-murano-node]
  tasks: &common_tasks
    - hiera
    - setup_repositories
    - fuel_pkgs
    - globals
    - tools
    - logging
    - netconfig
    - hosts
  required_for: [deploy_end]
  requires: [primary-controller]
  parameters:
    strategy:
      type: one_by_one

- id: murano-node
  type: group
  role: [murano-node]
  tasks: *common_tasks
  required_for: [deploy_end]
  requires: [primary-murano-node]
  parameters:
    strategy:
      type: parallel

- id: hiera-murano-override
  version: 2.1.0
  type: puppet
  groups: ['primary-controller', 'controller', 'primary-murano-node', 'murano-node']
  required_for: [logging]
  requires: [globals]
  parameters:
    puppet_manifest: manifests/murano_hiera_override.pp
    puppet_modules: /etc/puppet/modules
    timeout: 120
  # reexecute_on is needed for scale-down operations
  reexecute_on:
    - deploy_changes

- id: pin-murano-plugin-repo
  version: 2.1.0
  type: puppet
  groups: ['primary-controller', 'controller', 'primary-murano-node', 'murano-node' ]
  required_for: [hiera-murano-override]
  requires: [globals]
  parameters:
    puppet_manifest: manifests/pin_murano_plugin_repo.pp
    puppet_modules: /etc/puppet/modules
    timeout: 120
  # reexecute_on is needed for scale-down operations
  reexecute_on:
    - deploy_changes

- id: murano-keystone-endpoints
  version: 2.1.0
  type: puppet
  groups: ['primary-controller']
  required_for: [murano-controller-end]
  requires: [primary-keystone, keystone]
  cross-depends:
    - name: keystone
  parameters:
    puppet_manifest: manifests/murano_keystone.pp
    puppet_modules: /etc/puppet/modules:modules
    timeout: 1800
  # reexecute_on is needed for scale-down operations
  reexecute_on:
    - deploy_changes

- id: murano-database
  version: 2.1.0
  type: puppet
  groups: ['primary-controller']
  cross-depends:
    - name: /(primary-)?database/
  required_for: [murano-controller-end]
  requires: [primary-database, database]
  parameters:
    puppet_manifest: manifests/murano_db.pp
    puppet_modules: /etc/puppet/modules:modules
    timeout: 1800
  # reexecute_on is needed for scale-down operations
  reexecute_on:
    - deploy_changes

- id: murano-dashboard
  version: 2.1.0
  type: puppet
  groups: ['primary-controller','controller']
  required_for: [murano-controller-end]
  requires: [horizon]
  parameters:
    puppet_manifest: manifests/murano_dashboard.pp
    puppet_modules: /etc/puppet/modules:modules
    timeout: 1800
  # reexecute_on is needed for scale-down operations
  reexecute_on:
    - deploy_changes

- id: murano-controller-end
  version: 2.1.0
  type: skipped
  groups: ['primary-controller','controller']
  required_for: [deploy_end]
  requires: []

- id: murano-update-openrc
  version: 2.1.0
  type: puppet
  groups: ['primary-controller', 'controller']
  required_for: [murano-controller-end]
  requires: [primary-keystone, keystone]
  cross-depends:
    - name: keystone
  parameters:
    puppet_manifest: manifests/update_openrc.pp
    puppet_modules: /etc/puppet/modules
    timeout: 120
  # reexecute_on is needed for scale-down operations
  reexecute_on:
    - deploy_changes

- id: murano-haproxy
  version: 2.1.0
  type: puppet
  groups: ['primary-controller', 'controller']
  required_for: [murano-controller-end]
  requires: [deploy_start, primary-cluster-haproxy, cluster-haproxy]
  cross-depends:
    - name: /(primary-)?cluster-haproxy/
      role: self
  parameters:
    puppet_manifest: manifests/murano_haproxy.pp
    puppet_modules: /etc/puppet/modules
    timeout: 300
  # reexecute_on is needed for scale-down operations
  reexecute_on:
    - deploy_changes

- id: murano-logging
  version: 2.1.0
  type: puppet
  groups: ['primary-controller', 'controller', 'primary-murano-node', 'murano-node']
  required_for: [murano-services]
  requires: [logging]
  parameters:
    puppet_manifest: manifests/murano_logging.pp
    puppet_modules: /etc/puppet/modules
    timeout: 1800

- id: murano-services
  version: 2.1.0
  type: puppet
  groups: ['primary-controller', 'controller', 'primary-murano-node', 'murano-node']
  required_for: [deploy_end]
  requires: [hosts]
  cross-depends:
    - name: murano-controller-end
  parameters:
    puppet_manifest: manifests/murano.pp
    puppet_modules: /etc/puppet/modules:modules
    timeout: 3600

- id: murano-node-rabbitmq
  version: 2.1.0
  type: puppet
  groups: ['primary-controller', 'controller', 'primary-murano-node', 'murano-node']
  required_for: [murano-services]
  requires: [hosts]
  parameters:
    puppet_manifest: manifests/murano_rabbitmq.pp
    puppet_modules: /etc/puppet/modules:modules
    timeout: 1800

- id: murano-node-cfapi
  version: 2.1.0
  type: puppet
  groups: ['primary-controller', 'controller', 'primary-murano-node', 'murano-node']
  required_for: [deploy_end]
  requires: [murano-services]
  parameters:
    puppet_manifest: manifests/murano_cfapi.pp
    puppet_modules: /etc/puppet/modules:modules
    timeout: 3600
  condition: "settings:detach-murano.murano_cfapi.value == true"

# Murano ssl tasks
- id: murano-ssl-keys-saving
  type: puppet
  version: 2.1.0
  groups: ['primary-controller', 'controller', 'primary-murano-node', 'murano-node']
  requires: [netconfig]
  condition:
    yaql_exp: >
      (($.public_ssl.horizon or $.public_ssl.services) and
         $.public_ssl.cert_source = 'user_uploaded' and
         changed($.public_ssl.cert_data)) or
       (changed($.get('use_ssl')) and len($.get('use_ssl', [])) > 0)
  required_for: [deploy_end]
  parameters:
    puppet_manifest: manifests/murano_ssl_keys_saving.pp
    puppet_modules: /etc/puppet/modules:modules
    timeout: 120

- id: murano-ssl-add-trust-chain
  type: puppet
  version: 2.1.0
  groups: ['primary-controller', 'controller', 'primary-murano-node', 'murano-node']
  requires: [murano-ssl-keys-saving]
  condition:
    yaql_exp: &public_ssl_enabled >
      (changed($.public_ssl) and
       ($.public_ssl.horizon or $.public_ssl.services)) or
      (changed($.get('use_ssl')) and (len($.get('use_ssl', [])) > 0))
  required_for: [hosts]
  parameters:
    puppet_manifest: manifests/murano_ssl_add_trust_chain.pp
    puppet_modules: /etc/puppet/modules:modules
    timeout: 120

- id: murano-ssl-dns-setup
  type: puppet
  version: 2.1.0
  groups: ['primary-murano-node', 'murano-node']
  requires: [murano-ssl-add-trust-chain]
  condition:
    yaql_exp: *public_ssl_enabled
  required_for: [hosts]
  parameters:
    puppet_manifest: manifests/murano_ssl_dns_setup.pp
    puppet_modules: /etc/puppet/modules:modules
    timeout: 120
#####

# skip base murano tasks
- id: murano
  type: skipped

- id: murano-db
  type: skipped

- id: murano-keystone
  type: skipped

- id: murano-rabbitmq
  type: skipped

- id: murano-cfapi
  type: skipped

- id: murano-cfapi-keystone
  type: skipped

- id: upload_murano_package
  type: skipped
