#!/bin/bash
set -eux

. "$(dirname "$(readlink -f "$0")")"/functions.sh

VERSION_FILE="build_version"
MURANO_REF=${MURANO_REF:-'stable/mitaka'}
MURANO_PACKAGE_RELEASE=${MURANO_PACKAGE_RELEASE:-'9.0'}
MURANO_TARBALL_URL=${MURANO_TARBALL_URL:-"https://github.com/openstack/puppet-murano/archive/${MURANO_REF}.tar.gz"}

# Add murano packages and some dependencies, from master pkg's
MURANO_PACKAGES_URLS_DEFAULT="http://mirror.fuel-infra.org/extras/murano-plugin-repos/ubuntu/${MURANO_PACKAGE_RELEASE}/pool/main/"

MURANO_PACKAGES_URLS=${MURANO_PACKAGES_URLS:-${MURANO_PACKAGES_URLS_DEFAULT}}

for url in ${MURANO_PACKAGES_URLS}; do
  download_package 'deb' "${url}"
done

download_puppet_module "murano" ${MURANO_TARBALL_URL}

# generate general version file
generate_version_file "${VERSION_FILE}"

# add info about MURANO_TARBALL
echo "MURANO_TARBALL_URL=${MURANO_TARBALL_URL}" >> "${VERSION_FILE}"
echo "MURANO_TARBALL_COMMIT=$(git ls-remote -h https://github.com/openstack/puppet-murano.git |grep "refs/heads/${MURANO_REF}" |awk '{print $1}' )" >> "${VERSION_FILE}"


